<?php

$modversion['name'] = 'i-Diary';
$modversion['version'] = '1.02';
$modversion['description'] = 'i-Diary for XOOPS Ver1.0 based on Original ver2.0';
$modversion['author'] = 'http://www.martin.bz/';
$modversion['credits'] = 'Modularized into XOOPS by HAL (http://www.adslnet.org/)';
$modversion['help'] = '';
$modversion['license'] = 'GPL';
$modversion['official'] = 1;
$modversion['image'] = 'images/ilogo.png';
$modversion['dirname'] = 'iDiary';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!

$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)

$modversion['tables'][0] = 'idiary_config';
$modversion['tables'][1] = 'idiary_myholiday';

// Menu
$modversion['hasMain'] = 1;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'idiary_search';

// Blocks
$modversion['blocks'][1]['file'] = 'block.php';
$modversion['blocks'][1]['name'] = '新着日記';
$modversion['blocks'][1]['description'] = '新しい日記を表示します';
$modversion['blocks'][1]['show_func'] = 'b_idiary_block';
$modversion['blocks'][1]['options'] = '5';
$modversion['blocks'][1]['edit_func'] = 'b_idiary_block_edit';
$modversion['blocks'][1]['template'] = 'idiary_recent_block.html';

// Menu
$modversion['hasMain'] = 1;

// Templates
//$modversion['templates'][1]['file'] = '';
//$modversion['templates'][1]['description'] = '';

// Extra install/uninstall script for this module
//$modversion['onInstall'] = 'include/functions.php';
//$modversion['onUninstall'] = 'include/functions.php';
